plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.4'
	id 'io.spring.dependency-management' version '1.1.7'
}
// build.gradle
bootJar {
	mainClass.set('com.deefacto.ai_service.AiServiceApplication')
}

group = 'com.deefacto'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}


configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}


dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// AWS SDK v2 - S3
    implementation platform('software.amazon.awssdk:bom:2.20.110')
    implementation 'software.amazon.awssdk:s3'

	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'mysql:mysql-connector-java:8.0.33'

	// Redis 의존성
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
}

// build.gradle 파일 하단에 추가
tasks.register('printProjectName') {
	doLast {
		println project.name
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
